---
driver:
  name: docker

provisioner:
  name: chef_zero
  product_name: chef
  deprecations_as_errors: true
  multiple_converge: 2
  enforce_idempotency: true

verifier:
  name: inspec

platforms:
  - name: debian
    driver_config:
      use_sudo: false

suites:
  - name: default
    run_list:
      - recipe[fluentbit::default]
      - recipe[fluentbit::_example]
    attributes:
      fluentbit:
        conf:
          Daemon: "On"
