language: ruby
sudo: required
dist: trusty
group: edge # https://github.com/travis-ci/travis-ci/issues/5448
services:
  - docker
rvm:
  - 2.7.1
  - 2.6.6
  - 2.5.8
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
  - gem --version
script:
  - bundle exec rake
