language: ruby
sudo: required
dist: trusty
group: edge # https://github.com/travis-ci/travis-ci/issues/5448
services:
  - docker
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
  - gem --version
script:
  - bundle exec rake
