language: ruby
sudo: required
dist: trusty
group: edge # https://github.com/travis-ci/travis-ci/issues/5448
services:
  - docker
rvm:
  - 2.5.1
  - 2.4.4
  - 2.3.7
before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
  - gem --version
script:
  - bundle exec rake
